name: "😵 Bug report"
description: "버그 발생 관련 이슈시 사용하는 템플릿입니다. Bug report template"
title: "[Bug] "
labels: ["Bug"]
body:
  - type: dropdown
    id: environment
    attributes:
      label: "🌐 발생 환경 Environment"
      options:
        - Production (실제 서비스 환경)
        - Development (개발 환경)
        - Test (테스트 환경)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "📌 버전 Version"
      placeholder: "v1.0.0"
      description: "버전이 명시되어있지 않다면 관련 이슈나 브랜치의 태그 번호를 입력해주세요.(추가 정보란에 태그번호 필수 기재)\nIf no version is specified, please enter the number of the tag for the relevant issue or branch.(Tag number must be entered in the additional information field)"
    validations:
      required: true

  - type: input
    id: file-path
    attributes:
      label: "📂 파일 위치 Path"
      placeholder: "Source/Data/Login.swift"
      description: "버그가 발생한 파일 경로를 입력해주세요.\nPlease enter the path to the file where the bug occurred."

  - type: textarea
    id: description
    attributes:
      label: "📝 버그 설명 Bug Description"
      placeholder: |
        예시 Ex:
        - 로그인 버튼 클릭 시 화면이 멈추는 현상이 발생합니다. When I click the login button, the screen freezes.
        - 이메일 입력 후 로그인 시도할 때마다 발생합니다. This happens every time I try to log in after entering my email.
        - 로그인 기능 전체를 사용할 수 없습니다. The login feature is completely unavailable.
      description: "어떤 문제가 발생했나요? 어떤 상황에서 발생했나요? 어떤 기능에 영향을 미치나요?\nWhat problem occurred? Under what circumstances did it occur? What function does it affect?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📷 스크린샷 및 로그 Screenshots and logs"
      description: "스크린샷이나 로그를 이곳에 첨부해주세요. Please attach screenshots or logs here."

  - type: textarea
    id: additional
    attributes:
      label: "ℹ️ 추가 정보 Additional information"
      placeholder: |
        예시 Ex:
        - (버전을 명시하지 않았을 경우 필수 입력)관련 이슈: #42, #123 (Required if version not specified) Related issues: #42, #123
        - 기타 참고 사항 Other Notes
      description: "문제 해결에 도움이 될 만한 추가 정보가 있다면 작성해주세요. Please provide any additional information that may help us troubleshoot your issue."
